name: Terraform Apply
permissions:
  id-token: write
  contents: write
  checks: write
  security-events: write
  actions: write
  pull-requests: write

on:
  push:
    branches:
      - main
    paths:
      - finisterra/**

env:
  TERRAFORM_VERSION: "1.5.0"
  TERRAGRUNT_VERSION: "0.50.4"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get the PR description
        id: pr-description
        run: |
          # Extract the PR number from the commit message of the recent push.
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          PR_NUMBER=$(echo "$COMMIT_MESSAGE" | grep -oP 'Merge pull request #\K\d+')

          # Ensure we found a PR number before proceeding.
          if [[ -z "$PR_NUMBER" ]]; then
            echo "Could not determine PR number from commit message. Exiting."
            exit 0
          fi

          # Get the description of the PR using its number.
          PR_DESCRIPTION=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            --max-time 300 \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER | \
            jq -r '.body')

          if [[ "$PR_DESCRIPTION" == *"[skip cicd]"* ]]; then
            echo "Setting output to skip apply."
            echo "skip_cicd=true" >> $GITHUB_OUTPUT
          fi

      - name: Get updated folders
        id: get-folders
        uses: finisterra-io/gha-updated-folders@main

    outputs:
      folders: ${{ steps.get-folders.outputs.folders }}
      skip_cicd: ${{ steps.pr-description.outputs.skip_cicd }}

  run_terragrunt:
    needs: [setup]
    if: needs.setup.outputs.folders != '[]'
    name: ${{ matrix.service.service_name }}-${{ matrix.service.aws_account_id }}-${{ matrix.service.aws_region }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: ${{fromJson(needs.setup.outputs.folders)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set AWS Credentials
        id: set-aws-credentials
        uses: finisterra-io/gha-set-aws-credentials@main
        with:
          folder: ${{ matrix.service.folder }}

      - name: Terraform ${{ matrix.service.service_name }}-${{ matrix.service.aws_account_id }}-${{ matrix.service.aws_region }}
        uses: datadrivers/terragrunt-action@v0.10.2
        with:
          github-token: ${{ github.token }}
          terraform-version: ${{ env.TERRAFORM_VERSION }}
          terragrunt-version: ${{ env.TERRAGRUNT_VERSION }}
          use-aws-auth: false
          enable-terraform-change-pr-commenter: false
          terragrunt-working-directory: ${{ matrix.service.folder }}
          terragrunt-command: |
            if [ "${{ needs.setup.outputs.skip_cicd }}" == "true" ]
            then
              echo "Runnng terragrunt refresh"
              terragrunt refresh
            elif [[ ! -f "terragrunt.hcl" ]]; then
              echo "No resources found for ${AWS_MODULE}"
              exit 0
            else
              terragrunt apply -lock-timeout=10m --terragrunt-non-interactive --auto-approve
            fi
